DROP TABLE `wf_users`;
DROP TABLE `wf_user_devices`;
DROP TABLE `wf_groups`;
DROP TABLE `wf_policies`;
DROP TABLE `wf_pins`;
DROP TABLE `wf_user_groups`;
DROP TABLE `wf_group_policies`;
DROP TABLE `wf_pin_policies`;
DROP TABLE `wf_daily_usage`;