# this file is used only in development to watch golang files and recompile when a change is detected
settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  host: localhost
  port: 5001
schema:
- name: server
  path: .
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    paths:
      - /
    extensions:
      - go
      - html
    ignored_paths:
      - .git
      - vendor
      - resources
      - api_test