settings:
  legacy:
    force: false
    interval: 100ms
schema:
- name: server
  path: .
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - html
    ignored_paths:
    - vendor
    - resources
    - api_test