serverConfigs:
 prefix : 'CORE'
 isMaster : true
 portOffset : 0
 httpPort : 8080
 httpsPort : 8085
 adminPort : 9463
 caddyPort : 8082
 readTimeOut : 20
 writeTimeOut : 20
 certificateFile : '{{.ServerHome}}/resources/security/server.pem'
 keyFile : '{{.ServerHome}}/resources/security/server.key'
 JWTPrivateKeyFile : '{{.ServerHome}}/resources/security/private.key'
 JWTPublicKeyFile : '{{.ServerHome}}/resources/security/public.key'
 JWTExpirationDelta : 72
 caddyPath : '{{.ServerHome}}/webapps'
 caddyFile : '{{.ServerHome}}/webapps/Caddyfile'
 logsDirectory : 'logs'
 logLevel : 'info'
 enableAccessLogs : true

redisConfigs:
 address : "localhost:6379"
 password : vampspass

dbConfigs:
 -
  name : platform
  dialect : mysql
  username : root
  password : root
  dbname : vamps
  address : 'localhost:3306'
  parameters : ""
 -
  name : userstore
  dialect : mysql
  username : root
  password : root
  dbname : vamps
  address : 'localhost:3306'
  parameters : ""

